CREATE TABLE BOOKS (
	CHUNK_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ISBN CHAR(13) NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	AUTHOR_FIRST_NAME VARCHAR(25) NOT NULL,
	AUTHOR_LAST_NAME VARCHAR(25) NOT NULL,
	CHUNK VARCHAR(MAX) NOT NULL,
	EMBEDDED_CHUNK VECTOR(1024) NOT NULL
)